services:
  caddy:
    image: caddy:2.11.4-alpine
    container_name: caddy
    networks:
      - homelab
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - path: .env
        required: true
    volumes:
      - caddy:/data/
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/extras:/etc/caddy/extras
    restart: unless-stopped
  rathole:
    image: rapiz1/rathole
    container_name: rathole
    command: --client /etc/rathole/client.toml
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - ./config/rathole/client.toml:/etc/rathole/client.toml
    restart: unless-stopped
  samba:
    image: dockurr/samba
    container_name: samba
    networks:
      - homelab
    ports:
      - 445:445
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data:/shared
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    command: --config /config/settings.json --address 0.0.0.0
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - filebrowser:/config
      - ./data:/data
      - ./config/filebrowser/settings.json:/config/settings.json
    restart: unless-stopped
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    container_name: silverbullet
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data/notes:/space
    restart: unless-stopped
  polaris:
    image: registry.gitlab.com/connectical/container/polaris
    container_name: polaris
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - polaris:/var/lib/polaris
      - ./data/music:/music:ro
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - jellyfin:/config
      - ./data/movies:/media:ro
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - homelab
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    env_file:
      - path: .env
        required: true
    volumes:
      - qbittorrent:/config
      - ./data/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  harmon:
    image: heraclitoqsaldanha/harmon-server:latest
    container_name: harmon
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - harmon:/data/
      - ./config/harmon/:/config/
    restart: unless-stopped

volumes:
  caddy:
  polaris:
  jellyfin:
  qbittorrent:
  filebrowser:
  harmon:

networks:
  homelab:
    name: homelab
    driver: bridge
